### PR TITLE
Updated everything and streamlined the installation/start process

### PR DESCRIPTION
**Pull request by bartekus**
I've taken the liberty of updating everything along with fixing and streamlining the overall process.

### CODE REVIEW

**Comment by eh3rrera** [comment]
Thank you @Bartekus, you're awesome. I just tested your branch and works great.

I started updating the application but got a little stuck at the authentication part (it seems that an initial token is now required). 

Some comments:
- I think the directory `.idea/dictionaries` should not be part of the repo as it's IDE specific.
- In login.js, why `/horizon/github` is assigned to `window.location.pathname` instead of `endpoint`?
- I don't know if it's best to wait until horizon 2.0 is officially released to merge this pull request, in case something else changes or more fixes are required.

Great work, thanks again.

**Comment by bartekus** [comment]
Hello @eh3rrera, no problem good sir, I'm more than happy to contribute to a great cause and if it wasn't for your work I wouldn't be able to grok things as fast as I can now.

In either way, the .idea/ folder in the commit is my bad, I usually add it to .gitignore right away but it seems I didn't do it this time, opss sorry :D

As to the login.js, the reason for assigning `/horizon/github/` to `window.location.pathname` is that `endpoint` in this case refers to `https://localhost:8181/horizon/github/` so what we end up with `https://localhost:8181/https://localhost:8181/horizon/github/` otherwise.
It's a hacky way and I'm sure there is probably a better solution to resolve this.

I agree that perhaps until horizon 2.0 comes out officially this pull should not be merged.

That being said, I'll be monitoring for additional changes and update this pull as necessery.

**Comment by eh3rrera** [comment]
That's the spirit @Bartekus! Thank you!

**Comment by eh3rrera** [comment]
Hi @Bartekus, just to mention (maybe you already know) that Horizon is on beta 6 already. I just tested that the following changes work now:
- In horizon-container.js, we can have `authType: 'token'` (https://github.com/rethinkdb/horizon/issues/663) and the line `_horizon.connect();` can be removed now (https://github.com/rethinkdb/horizon/issues/749)
- In login.js, we can use `window.location.replace(endpoint)` (https://github.com/rethinkdb/horizon/issues/663 at the end of the conversation).

**Pull request merged**
